In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("C:/Users/hp r5/OneDrive/Desktop/Data Analyst Portfolio/customer_shopping_behavior.csv")

In [4]:
df.head(5)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Customer ID,3900,NaN,NaN,NaN,1950.5,1125.98,1,975.75,1950.5,2925.25,3900
Age,3900,NaN,NaN,NaN,44.0685,15.2076,18,31,44,57,70
Gender,3900,2,Male,2652,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Item Purchased,3900,25,Pants,171,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,3900,4,Clothing,1737,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Purchase Amount (USD),3900,NaN,NaN,NaN,59.7644,23.6854,20,39,60,81,100
Location,3900,50,Montana,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Size,3900,4,M,1755,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Color,3900,25,Olive,177,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Season,3900,4,Spring,999,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Review Rating,3863,NaN,NaN,NaN,3.75006,0.716983,2.5,3.1,3.8,4.4,5
Subscription Status,3900,2,No,2847,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Shipping Type,3900,6,Free Shipping,675,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Discount Applied,3900,2,No,2223,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Promo Code Used,3900,2,No,2223,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Previous Purchases,3900,NaN,NaN,NaN,25.3515,14.4471,1,13,25,38,50
Payment Method,3900,6,PayPal,677,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Frequency of Purchases,3900,7,Every 3 Months,584,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [7]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [8]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [10]:
# Allways putt the column name into the snake cases :- lower and underscore
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace("-","_")

In [11]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [13]:
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [14]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [15]:
#Create a  colume age_group

labels=['Young Adult','Adult','Middle_aged','Senior']
df['age_grouped']=pd.qcut(df['age'],q=4,labels=labels)

In [17]:
df[['age','age_grouped']].head(5)

   age  age_grouped
0   55  Middle_aged
1   19  Young Adult
2   50  Middle_aged
3   21  Young Adult
4   45  Middle_aged

In [18]:
df['frequency_of_purchases'].unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [19]:
# Purchase  frequency rate
frequency_mapping={
    'Fortnightly':14
    ,'Weekly':7
    ,'Annually':365
    ,'Quarterly':90
    ,'Bi-Weekly':14
    ,'Monthly':30
    ,'Every 3 Months':90}

df['purchase_freuency']=df['frequency_of_purchases'].map(frequency_mapping)

In [23]:
df[["purchase_amount","frequency_of_purchases","purchase_freuency"]].head(5)

   purchase_amount frequency_of_purchases  purchase_freuency
0               53            Fortnightly                 14
1               64            Fortnightly                 14
2               73                 Weekly                  7
3               90                 Weekly                  7
4               49               Annually                365

In [28]:
df[['discount_applied','promo_code_used']].head(5)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes

In [ ]:
# we checked that the both columns contain the same data
(df["discount_applied"]==df['promo_code_used']).all()

True

In [30]:
df=df.drop('promo_code_used',axis=1)

In [31]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_grouped', 'purchase_freuency'],
      dtype='object')

In [33]:
# for connecting install the dependeancy
!pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2-binary-2.9.8.tar.gz (383 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting sqlalchemy
  Downloading sqlalchemy-1.4.54.tar.gz (8.5 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: importlib-metadata in d:\anaconda\envs\deepl\lib\site-packages (from sqlalchemy) (4.8.1)
Collecting greenlet!=0.4.17
  Downloading greenlet-2.0.2-cp36-cp36m-win_amd64.whl (197 kB)
Requirement already satisfied: typing-extensions>=3.6.4 in d:\anaconda\envs\deepl\lib\site-packages (from importlib-metadata->sqlalchemy) (4.1.1)
Requirement already satisfied: zipp>=0.5 in c:\users\hp r5\appdata\roaming\python\python36\site-packages (from importlib-metadata->sqlalchemy) (3.6.0)
Building wheels for collected packages: psycopg2-binary, sqlalchemy
  Building wheel for psycopg2-binary (setup.py): started
  Building wheel for psycopg2-binary (setup.py): finished with status 'done'
  Created wheel for psycopg2-binary: filename=psycopg2_binary-2.9.8-cp36-cp36m-win_amd64.whl size=151223 sha256=8c90380cab6997d1170c3950cafb7edd1c600d1f271095704d056d380b696422
  Stored in directory: c:\users\hp r5\appdata\local\pip\cache\wheels\df\38\b5\59a6f18a73f24dccc53e7bafa8ec4def176aa8b84f3e39e10d
  Building wheel for sqlalchemy (setup.py): started
  Building wheel for sqlalchemy (setup.py): finished with status 'done'
  Created wheel for sqlalchemy: filename=SQLAlchemy-1.4.54-cp36-cp36m-win_amd64.whl size=1581463 sha256=f8f87ea828166fc19717ea7e2f63bc91039011297cdf677e7a52b57a5aac7dd7
  Stored in directory: c:\users\hp r5\appdata\local\pip\cache\wheels\a0\16\20\3d1ee90d2eb7e56e146d6c52f1eaf9f9b117c5825cf648212c
Successfully built psycopg2-binary sqlalchemy
Installing collected packages: greenlet, sqlalchemy, psycopg2-binary
Successfully installed greenlet-2.0.2 psycopg2-binary-2.9.8 sqlalchemy-1.4.54

WARNING: Ignoring invalid distribution -iwisolver (d:\anaconda\envs\deepl\lib\site-packages)
WARNING: Ignoring invalid distribution -iwisolver (d:\anaconda\envs\deepl\lib\site-packages)
WARNING: Ignoring invalid distribution -iwisolver (d:\anaconda\envs\deepl\lib\site-packages)
WARNING: Ignoring invalid distribution -iwisolver (d:\anaconda\envs\deepl\lib\site-packages)
WARNING: Ignoring invalid distribution -iwisolver (d:\anaconda\envs\deepl\lib\site-packages)
WARNING: Ignoring invalid distribution -iwisolver (d:\anaconda\envs\deepl\lib\site-packages)
WARNING: Ignoring invalid distribution -iwisolver (d:\anaconda\envs\deepl\lib\site-packages)
WARNING: Ignoring invalid distribution -iwisolver (d:\anaconda\envs\deepl\lib\site-packages)

In [40]:
#Connecting setup to PostgreSQl
from sqlalchemy import create_engine
username='postgres'
password='7984'
host='localhost'
port='5432'
database='Customer_behaviour'


engine=create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")


try:
    with engine.connect() as conn:
        print("Connected Succefully")
except Exception as e:
    print("Error:",e)

ImportError: DLL load failed: The specified module could not be found.